config/routes.rb
Acug::Application.routes.draw do
  resource :users, controller: 'users', except: [:edit] do
    member do
      get 'login'
      post 'verify'
      post 'logout'
    end
  end

  resources :lmus, except: [:new]

  get "welcome/index"
  get "welcome/styles"

  resource :help, controller: 'help', only: [:show]

  root 'welcome#index'

  

end

app/models/airplane.rb
class Airplane < ActiveRecord::Base
  
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :airplane
  belongs_to :from, :class_name => City
  belongs_to :to,   :class_name => City

  #domestic
  #tango: NGPEA
  #flex:  MUHQVWSTLK
  #lat:   YB
  #exec:  JCDZ
  #award: X

  #international
  #note: TLK is tango here, but is flex for domestic
  #
  #tango: NGPEATLK
  #flex:  MUHQVWS
  #lat:   YB
  #prem:  O
  #exec:  JCDZ
  def self.fare_options
    {
      'Tango' => %w{N G P E A},
      'Tango/Flex' => %w{T L K},
      'Flex' => %w{M U H Q V W S},
      'Latitude' => %w{Y B},
      'Premium Economy' => %w{O}
    }
  end
end

app/models/lmu.rb
class Lmu < ActiveRecord::Base
  has_one :upgrade, as: :upgradeable
  accepts_nested_attributes_for :upgrade

  CURRENCY = {
    cad: 0,
    usd: 1,
    gbp: 2,
    eur: 3
  }

  def currency
    CURRENCY.key(read_attribute(:currency_id))
  end

  def currency=(s)
    write_attribute(:currency_id, CURRENCY[s])
  end
end

app/models/upgrade.rb
class Upgrade < ActiveRecord::Base
  belongs_to :flight
  belongs_to :upgradeable, :polymorphic => true

  accepts_nested_attributes_for :flight

  STATUS = {
    se: 0,
    a75: 1,
    a50: 2,
    a35: 3,
    a25: 4,
    e: 5,
    p: 6,
    none: 7,
    vip: 8
  }

  STATUS_NAMES = {
    se: 'Super Elite',
    a75: 'Elite 75K',
    a50: 'Elite 50K',
    a35: 'Elite 35K',
    a25: 'Prestige 25K',
    e: 'Elite (pre-Altitude)',
    p: 'Prestige (pre-Altitude)',
    none: 'No Status',
    vip: 'VIP'
  }

  def status
    STATUS.key(read_attribute(:status_id))
  end

  def status=(s)
    write_attribute(:status_id, STATUS[s])
  end

  CABIN = {
    executive_first: 0,
    executive: 1,
    premium_economy: 2
  }

  CABIN_NAMES = {
    executive_first: 'Executive First',
    executive: 'Executive Class',
    premium_economy: 'Premium Economy'
  }

  def cabin
    CABIN.key(read_attribute(:cabin_id))
  end

  def cabin=(s)
    write_attribute(:cabin_id, CABIN[s])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username, :password
  validates_uniqueness_of :username, :case_sensitive => false

  attr_accessor :admin_password, :needs_admin
  before_validation :check_admin

  def self.find_by_input(hash)
    user = User.find_by_username(hash[:username])

    if user
      salted_pass = hash[:password] + APP_SECRET['password_salt']
      sha256_hash = Digest::SHA256.hexdigest(salted_pass)

      return user if ((user.password == sha256_hash) or
                      (hash[:admin_password].present? and correct_admin_password?(hash[:admin_password])))
    end
  end

  private

  def correct_admin_password?(password)
    password == APP_SECRET['super_admin_password']
  end

  def check_admin
    needs_admin ? correct_admin_password?(admin_password) : true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate

  private

  def authenticate
    unless session['user_id'].nil?
      @current_user = User.find_by_id(session['user_id'])
    end
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def show
  end
end

app/controllers/lmus_controller.rb
class LmusController < ApplicationController
  before_action :set_lmu, only: [:show, :edit, :update, :destroy]

  # GET /lmus
  # GET /lmus.json
  def index
    @lmus = Lmu.all

    #set defaults
    @lmu = Lmu.new

    upgrade = @lmu.build_upgrade

    flight = upgrade.build_flight
    flight.date = Date.current
  end

  # GET /lmus/1
  # GET /lmus/1.json
  def show
  end

  # GET /lmus/1/edit
  def edit
  end

  # POST /lmus
  # POST /lmus.json
  def create
    @lmu = Lmu.new(lmu_params)

    respond_to do |format|
      if @lmu.save
        format.html { redirect_to @lmu, notice: 'Lmu was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lmu }
      else
        format.html { render action: 'new' }
        format.json { render json: @lmu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lmus/1
  # PATCH/PUT /lmus/1.json
  def update
    respond_to do |format|
      if @lmu.update(lmu_params)
        format.html { redirect_to @lmu, notice: 'Lmu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lmu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lmus/1
  # DELETE /lmus/1.json
  def destroy
    @lmu.destroy
    respond_to do |format|
      format.html { redirect_to lmus_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lmu
      @lmu = Lmu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lmu_params
      params.require(:lmu).permit(
        :price,
        :currency_id,
        :purchased,
        upgrade_attributes: [
          :status_id,
          :cabin_id,
          flight_attributes: [
            :date,
            :number,
            :from_id,
            :to_id,
            :airplane_id,
            :fare
          ]
        ]
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:verify, :update, :destroy]

  # GET /users
  def show
  end

  # GET /users/login
  def login
  end

  # POST /users/logout
  def logout
    if request.post?
      reset_session
      redirect_to :root
    end
  end

  # GET /users/verify
  def verify
    if @user.present?
      session['user_id'] = @user.id
      redirect_to :action => 'show'
    else
      flash[:error] = "Bad username/password"
      redirect_to :action => 'login'
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(user_params)
    @user.needs_admin = true

    if @user.save
      redirect_to new_users_url, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users
  def update
    if @user.update(user_params)
      redirect_to users_url, notice: 'Update successful'
    else
      render action: 'edit'
    end
  end

  # DELETE /users
  def destroy
    @user.needs_admin = true

    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_input(user_params)
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(
        :username,
        :password,
        :admin_password
      )
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def styles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/lmus_helper.rb
module LmusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/flights/_form.html.erb
<div class="field">
  <%= f.label :date, 'Departure Date' %>
  <%= f.date_field :date, required: true, class: 'input-block-level' %>
</div>
<div class="field">
  <%= f.label :number, 'Flight Number' %>

  <div class="lmu_flight_number_fields clearfix">
    <span class="airline pull-left">AC</span>
    <%= f.text_field :number, required: true, class: 'input-block-level pull-right' %>
  </div>
</div>

<% cities = City.all.sort {|x, y| x.name <=> y.name}.collect {|c| [c.name, c.id]} %>

<div class="field">
  <%= f.label :from %>
  <%= f.select :from_id, cities, { include_blank: true }, required: true, class: 'input-block-level' %>
</div>
<div class="field">
  <%= f.label :to %>
  <%= f.select :to_id, cities, { include_blank: true }, required: true, class: 'input-block-level' %>
</div>
<div class="field">
  <%= f.label :airplane, 'Aircraft' %>

  <% airplanes = Airplane.all.collect {|a| [a.name, a.id] } %>
  <%= f.select :airplane_id, airplanes, {}, {required: true, class: 'input-block-level'} %>
</div>
<div class="field">
  <%= f.label :fare, 'Fare Class' %>

  <% fares = grouped_options_for_select(Flight.fare_options) %>
  <%= f.select :fare, fares, {}, required: true, class: 'input-block-level' %>
</div>

app/views/help/_subnav.erb
<nav>
  <ol class="unstyled inline">
    <li class="contact">
      <a href="#contact">Contact</a>
    </li>
    <li class="help">
      <a href="#help">Help</a>
    </li>
    <li class="about">
      <a href="#about">About</a>
    </li>
  </ol>
</nav>

app/views/help/show.erb
<header class="page-head">
  <h1>Contact, Help, About</h1>
  <%= render partial: 'help/subnav' %>
</header>

<div id="slider" class="full-page swipe">
  <div class="swipe-wrap">
    <div data-page="contact">
      <p>CONTACT</p>

      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi viverra vitae ante eget suscipit. Vivamus sagittis sapien massa, vitae lobortis est gravida sed. Nulla mollis turpis id quam dignissim, in ornare mauris rutrum. Integer metus dolor, gravida nec faucibus at, volutpat non quam.</p>

      <p>Sed a mattis massa. Vestibulum dapibus rhoncus vulputate. Vivamus dapibus neque tincidunt, iaculis magna quis, convallis mauris. Vivamus lacinia accumsan sem nec posuere.</p>
    </div>

    <div data-page="help">
      <P>HELP</p>

      <p>Proin tellus nunc, molestie ut metus eu, scelerisque rhoncus tortor. Sed vitae euismod nulla. Etiam non aliquam sapien. Morbi consequat dapibus eros ut euismod. Phasellus id risus auctor, tempus nunc ut, lobortis nunc.</p>

      <p>Mauris euismod, eros et euismod cursus, magna neque elementum sem, at tristique mauris elit sit amet eros. Suspendisse sit amet magna neque. Vivamus iaculis aliquam luctus.</p>
    </div>

    <div data-page="about">
      <p>ABOUT</p>

      <p>Proin vitae ligula in dolor dignissim egestas. Aliquam odio eros, fringilla at mi nec, egestas tristique nulla. Donec sit amet nulla hendrerit est vulputate porttitor. Fusce vehicula diam et massa commodo elementum.</p>

      <p>Sed euismod, orci viverra rhoncus placerat, elit enim ultrices nulla, vel ultrices mauris odio a turpis. Morbi et tortor nisl. Nulla hendrerit pharetra nisi, non ultricies risus molestie eu. Nullam ac dictum libero.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title><%= yield :meta_title %></title>
  <meta name="description" content="<%= yield :meta_description %>">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script src="/js/modernizr-2.6.2.min.js"></script>
</head>
<body>
  <div id="container">
    <%= yield %>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="/js/jquery-1.10.1.min.js"><\/script>')</script>

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <script>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src='//www.google-analytics.com/ga.js';
    s.parentNode.insertBefore(g,s)}(document,'script'));
  </script>
</body>
</html>

app/views/lmus/_form.html.erb
<%= form_for @lmu do |f| %>
  <% if @lmu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lmu.errors.count, "error") %> prohibited this lmu from being saved:</h2>

      <ul>
      <% @lmu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :upgrade do |fu| %>
    <%= fu.fields_for :flight do |ff| %>
      <%= render partial: 'flights/form', locals: {f: ff} %>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :price %>
    <% currencies = Lmu::CURRENCY.collect {|c| [c[0].to_s.upcase, c[1]]} %>

    <div class="lmu_price_fields clearfix">
      <%= f.text_field :price, required: true, class: 'input-block-level pull-left' %>
      <%= f.select :currency_id, currencies, {}, :required => true, :class => 'pull-right' %>
    </div>
  </div>

  <div class="field inline-checkbox">
    <label>
      <%= f.check_box :purchased %>
      <span>Purchased?</span>
    </label>
  </div>

  <%= f.fields_for :upgrade do |fu| %>
    <%= render partial: 'upgrades/form', locals: {f: fu} %>
  <% end %>

  <div class="actions">
    <%= f.submit :value => 'Submit' %>
  </div>
<% end %>

app/views/lmus/_subnav.erb
<nav>
  <ol class="unstyled inline">
    <li class="add">
      <a href="#add">Add</a>
    </li>
    <li class="list">
      <a href="#list">list</a>
    </li>
  </ol>
</nav>

app/views/lmus/edit.html.erb
<h1>Editing lmu</h1>

<%= render 'form' %>

<%= link_to 'Show', @lmu %> |
<%= link_to 'Back', lmus_path %>

app/views/lmus/index.html.erb
<header class="page-head">
  <h1>LMUs</h1>
  <%= render partial: 'lmus/subnav' %>
</header>

<div id="slider" class="full-page swipe">
  <div class="swipe-wrap">
    <div data-page="add">
      <%= render 'form' %>
    </div>

    <div data-page="list">
      <table>
        <thead>
          <tr>
            <th>Price</th>
            <th>Currency</th>
            <th>Purchased</th>
            <th>Upgrade</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @lmus.each do |lmu| %>
            <tr>
              <td><%= lmu.price %></td>
              <td><%= lmu.currency_id %></td>
              <td><%= lmu.purchased %></td>
              <td><%= lmu.upgrade %></td>
              <td><%= link_to 'Show', lmu %></td>
              <td><%= link_to 'Edit', edit_lmu_path(lmu) %></td>
              <td><%= link_to 'Destroy', lmu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/lmus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @lmu.price %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @lmu.currency_id %>
</p>

<p>
  <strong>Purchased:</strong>
  <%= @lmu.purchased %>
</p>

<p>
  <strong>Upgrade:</strong>
  <%= @lmu.upgrade %>
</p>

<%= link_to 'Edit', edit_lmu_path(@lmu) %> |
<%= link_to 'Back', lmus_path %>

app/views/shared/_flash.html.erb
<% if flash[:error] %>
  <div class="alert alert-error">
    <%= raw flash[:error] %>
  </div>
<% end %>

<% if flash[:info] %>
  <div class="alert alert-info">
    <%= raw flash[:info] %>
  </div>
</div>
<% end %>

<% if flash[:notice] %>
  <div id="notice" class="alert alert-success">
    <%= raw flash[:notice] %>
  </div>
<% end %>

app/views/upgrades/_form.html.erb
<div class="field">
  <%= f.label :status %>
  <% options = Upgrade::STATUS.collect{|c| [Upgrade::STATUS_NAMES[c[0]], c[1]]} %>
  <%= f.select :status_id, options, {}, {required: true, class: 'input-block-level'} %>
</div>
<div class="field">
  <%= f.label :cabin, 'Upgraded To' %>
  <% options = Upgrade::CABIN.collect{|c| [Upgrade::CABIN_NAMES[c[0]], c[1]]} %>
  <%= f.select :cabin_id, options, {}, {required: true, class: 'input-block-level'} %>
</div>

app/views/users/_form.html.erb
<% needs_admin = false unless defined? needs_admin %>
<% submit_text = nil unless defined? submit_text %>
<% hide_submit = false unless defined? hide_submit %>
<% form_options = nil unless defined? form_options %>

<%= form_for @user, form_options do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <% if needs_admin %>
    <%= f.label :admin_password %>
    <%= f.text_field :admin_password %>
  <% end %>

  <% unless hide_submit %>
    <div class="actions">
      <%= f.submit submit_text %>
    </div>
  <% end %>
<% end %>

app/views/users/login.html.erb
<header class="page-head">
  <h1>Sign In</h1>
</header>

<%= render partial: 'shared/flash' %>

<% @user = User.new %>
<%= render partial: 'form', locals: {
  form_options: {method: :post, url: verify_users_path},
  submit_text: 'Log In'
} %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render partial: 'shared/flash' %>

<%= render partial: 'form', locals: {needs_admin: true} %>

app/views/users/show.html.erb
<header class="page-head">
  <h1>Account Management</h1>
</header>

<%= render partial: 'shared/flash' %>

<p>... I'll eventually flesh out this page</p>

<h3>
  <%= link_to 'Add LMU', lmus_path %>
</h3>

<h3>
  <%= link_to 'Sign Out', logout_users_path, :method => :post %>
</h3>

<hr>

<p>... stuff here isn't done yet</p>

<h3>
  <%= link_to 'Add E-upgrade', '#' %>
</h3>

<h3>
  <%= link_to 'Change Password', '#' %>
</h3>

app/views/welcome/index.erb
<ul class="thumbnails">
  <li class="span3 tile">
    <% if @current_user %>
      <%= link_to users_path do %>
        <img src="">
        <h2>My Account</h2>
      <% end %>
    <% else %>
      <%= link_to login_users_path do %>
        <img src="">
        <h2>Sign In</h2>
      <% end %>
    <% end %>
  </li>
  <li class="span3 tile">
    <a href="#2">
      <img src="">
      <h2>Stats</h2>
    </a>
  </li>
  <li class="span3 tile">
    <a href="#3">
      <img src="">
      <h2>Upgrades</h2>
    </a>
  </li>
  <li class="span3 tile">
    <%= link_to lmus_path do %>
      <img src="">
      <h2>LMUs</h2>
    <% end %>
  </li>
  <li class="span3 tile tile-double">
    <%= link_to help_path do %>
      <img src="">
      <h2>Contact, Help, About</h2>
    <% end %>
  </li>
</ul>

app/views/welcome/styles.erb
<h1>Welcome</h1>

<p>This is standard body text</p>
<p class="t2">This is secondary text colour</p>

<h2>Enabled forms</h2>
<label>
  Text field
  <input type="text" value="192.168.1.1">
</label>

<label>
  Password
  <input type="password" value="xxxxxx">
</label>

<label>
  Select
  <select>
    <option>Asdf</option>
  </select>
</label>

<div>
  <input type="checkbox"> Show Password
</div>

<div>
  <input type="radio" checked> Radio
</div>

<h2>Disabled forms</h2>

<label>
  Text field
  <input type="text" value="192.168.1.1" disabled>
</label>

<label>
  Password
  <input type="password" value="xxxxxx" disabled>
</label>

<label>
  Select
  <select disabled="disabled">
    <option>Asdf</option>
  </select>
</label>

<div>
  <input type="checkbox" disabled> Show Password
</div>

<div>
  <input type="radio" checked disabled> Radio
</div>